const products = [
  {
    id: 1,
    code: "SPT001",
    name: '3 1/2" Lakshmi',
    category: "Sound Crackers",
    content: "1 PCS",
    mrp: 150,
    sellingPrice: 94,
    discount: 56,
    image: "/products/lakshmi.jpg",
  },
  {
    id: 2,
    code: "SPT002",
    name: '4" Lakshmi',
    category: "Sound Crackers",
    content: "1 PCS",
    mrp: 180,
    sellingPrice: 114,
    discount: 66,
    image: "/products/lakshmi.jpg",
  },
  {
    id: 3,
    code: "SPT003",
    name: '4" Deluxe Lakshmi',
    category: "Sound Crackers",
    content: "1 PCS",
    mrp: 200,
    sellingPrice: 130,
    discount: 70,
    image: "/products/deluxe-lakshmi.jpg",
  },
  {
    id: 4,
    code: "SPT004",
    name: "Gold Red Bijili",
    category: "Sound Crackers",
    content: "100 PCS",
    mrp: 234,
    sellingPrice: 199,
    discount: 35,
    image: "/products/bijili.jpg",
  },
  {
    id: 5,
    code: "SPT005",
    name: "Gold Stripped Bijili",
    category: "Sound Crackers",
    content: "100 PCS",
    mrp: 267,
    sellingPrice: 227,
    discount: 40,
    image: "/products/bijili.jpg",
  },
  {
    id: 6,
    code: "SPT006",
    name: '2 3/4" Kurvi',
    category: "Sound Crackers",
    content: "1 PCS",
    mrp: 60,
    sellingPrice: 51,
    discount: 9,
    image: "/products/kurvi.jpg",
  },
];

export default products;